######################################################################
# Automatically generated by qmake (2.01a) Thu May 29 17:37:01 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keypress.h \
    ui_keypress.h
FORMS += mainwindow.ui
SOURCES += keypress.cpp main.cpp
